version: '3.8'

services:
  traductor_client:
    build:
      context: ./client
    ports:
      - "5003:80"
    restart: unless-stopped
    depends_on:
      - traductor_server

  traductor_server:
    build:
      context: ./server
    ports:
      - "3003:3000"
    env_file:
      - .env
    restart: unless-stopped
