export const TEMARIO = [
 {code:"M0",from:"A1",to:"A1",title:"Arranque · Presentarse y el equipo",
  og:["Saludar, presentarse y despedirse","Deletrear nombres y correos","Números, horas y datos personales"],
  oi:["Nombrar el hardware básico de un puesto","Vocabulario del entorno de oficina"],
  vg:[["Hello / Goodbye","Hola / Adiós"],["My name is…","Me llamo…"],["Nice to meet you","Encantado"],["Could you spell that?","¿Puede deletrearlo?"],["phone number","número de teléfono"],["email address","correo"]],
  vi:[["computer / PC","ordenador"],["screen · monitor","pantalla"],["keyboard","teclado"],["mouse","ratón"],["cable","cable"],["power button","botón de encendido"],["headset","auriculares"],["workstation","puesto de trabajo"]],
  gr:["Verbo to be (am/is/are)","Pronombres personales","Artículos a / an / the"],
  ph:["My name is Manu and I work in IT support.","Can you spell your surname, please?"]},
 {code:"M1",from:"A1",to:"A2",title:"Rutinas · Mi jornada de soporte",
  og:["Hablar de rutinas diarias","Decir la hora, días y meses","Frecuencia (always, usually, never)"],
  oi:["Describir tu puesto y tus tareas","Describir la configuración de un equipo"],
  vg:[["to wake up","despertarse"],["to start work","empezar a trabajar"],["in the morning","por la mañana"],["every day","cada día"],["at 9 a.m.","a las 9"],["weekday / weekend","laborable / finde"]],
  vi:[["to log in / out","iniciar / cerrar sesión"],["to check emails","revisar el correo"],["to open a ticket","abrir un ticket"],["shift","turno"],["task","tarea"],["to set up","configurar"],["user account","cuenta de usuario"],["desktop","escritorio"]],
  gr:["Present Simple (afirm./neg./preg.)","Adverbios de frecuencia","do / does en preguntas"],
  ph:["I usually start my shift at 8 and check the ticket queue.","She logs in and opens the helpdesk tool."]},
 {code:"M2",from:"A2",to:"A2",title:"Describir · Problemas y síntomas",
  og:["Describir objetos con adjetivos","Colores, tamaños y cantidades","Expresar existencia (there is/are)"],
  oi:["Describir un fallo de hardware","Explicar síntomas de una incidencia"],
  vg:[["big / small","grande / pequeño"],["broken","roto"],["heavy / light","pesado / ligero"],["new / old","nuevo / viejo"],["there is / are","hay"]],
  vi:[["It doesn't work","No funciona"],["to freeze","colgarse"],["to crash","fallar / colapsar"],["error message","mensaje de error"],["slow","lento"],["to overheat","sobrecalentarse"],["blue screen","pantallazo azul"],["warning light","luz de aviso"]],
  gr:["there is / there are","Present Continuous (am + -ing)","have / has got"],
  ph:["The laptop is very slow and it keeps freezing.","There is an error message on the screen."]},
 {code:"M3",from:"A2",to:"B1",title:"Helpdesk · La primera llamada",
  og:["Etiqueta telefónica y cortesía","Peticiones educadas (can / could)","Deletrear y confirmar datos"],
  oi:["Abrir y registrar un ticket","Guiar en pasos básicos de troubleshooting"],
  vg:[["How can I help you?","¿En qué puedo ayudar?"],["Could you…, please?","¿Podría…?"],["Let me check","Déjeme comprobar"],["One moment, please","Un momento"],["to confirm","confirmar"]],
  vi:[["to restart / reboot","reiniciar"],["to unplug / plug in","desenchufar / enchufar"],["to update","actualizar"],["to reset the password","restablecer contraseña"],["ticket number","nº de ticket"],["remote access","acceso remoto"],["step by step","paso a paso"],["Did it work?","¿Funcionó?"]],
  gr:["Imperativos para instrucciones","can / could (peticiones)","should (consejos)"],
  ph:["Could you restart the computer and tell me what happens?","Let me open a ticket. Can you confirm your email?"]},
 {code:"M4",from:"A2",to:"B1",title:"Pasado · Qué ocurrió",
  og:["Hablar del pasado (finde, viajes)","Contar una secuencia de hechos","Preguntas en pasado"],
  oi:["Reportar qué pasó en una incidencia","Reconstruir el historial del problema"],
  vg:[["yesterday","ayer"],["last week","la semana pasada"],["I went / I saw","fui / vi"],["ago","hace (tiempo)"],["Then… / After that…","Luego… / Después…"]],
  vi:[["The system went down","El sistema se cayó"],["It happened when…","Ocurrió cuando…"],["to reproduce the error","reproducir el error"],["root cause","causa raíz"],["log file","registro / log"],["downtime","tiempo de inactividad"],["to restore","restaurar"],["to roll back","revertir"]],
  gr:["Past Simple (reg. e irreg.)","Past Continuous (was/were + -ing)","when / while"],
  ph:["The server went down at 3 p.m. when the user tried to save.","I checked the logs and found the root cause."]},
 {code:"M5",from:"B1",to:"B1",title:"Redes · Conectividad y configuración",
  og:["Dar y pedir direcciones","Preposiciones de lugar","Comparar (more / better / the best)"],
  oi:["Vocabulario de redes (IP, DNS, DHCP)","Diagnosticar y explicar problemas de red"],
  vg:[["next to / between","al lado de / entre"],["Turn left / right","Gire a la izq. / dcha."],["faster than","más rápido que"],["the best option","la mejor opción"]],
  vi:[["network","red"],["router / switch","router / switch"],["IP address","dirección IP"],["DNS / DHCP","DNS / DHCP"],["to ping","hacer ping"],["bandwidth","ancho de banda"],["latency","latencia"],["wired / wireless","cableado / inalámbrico"],["firewall","cortafuegos"],["to connect / disconnect","conectar / desconectar"]],
  gr:["Preposiciones de lugar y movimiento","Comparativos y superlativos","too / enough"],
  ph:["The wireless connection is slower than the wired one.","Try to ping the router to check if the network is up."]},
 {code:"M6",from:"B1",to:"B1",title:"Sistemas · Windows y Linux",
  og:["Explicar procesos paso a paso","Conectores (first, then, finally)","Voz pasiva básica"],
  oi:["Administrar SO (línea de comandos, permisos)","Comparar entornos Windows y Linux"],
  vg:[["first / then / finally","primero / luego / finalmente"],["is done / is created","se hace / se crea"],["in order to","para (finalidad)"],["make sure that…","asegúrate de que…"]],
  vi:[["operating system (OS)","sistema operativo"],["command line / terminal","línea de comandos"],["to run a command","ejecutar un comando"],["file / folder","archivo / carpeta"],["permissions","permisos"],["to install / uninstall","instalar / desinstalar"],["driver","controlador"],["distribution (distro)","distribución"],["admin / root rights","permisos de admin"],["to grant / revoke access","conceder / revocar acceso"]],
  gr:["Conectores de secuencia","Voz pasiva en presente (is/are + participio)","Gerundio tras preposición"],
  ph:["First, open the terminal; then run the command as administrator.","The update is installed automatically after the reboot."]},
 {code:"M7",from:"B1",to:"B1",title:"Ágiles · Scrum, Kanban y el Daily",
  og:["Reuniones: opinar, acordar y discrepar","Turnos de palabra","Planes (going to)"],
  oi:["Participar en un Daily Standup","Vocabulario de sprint, backlog y bloqueos"],
  vg:[["I agree / disagree","Estoy / No estoy de acuerdo"],["In my opinion…","En mi opinión…"],["Go ahead","Adelante"],["Let's move on","Sigamos"]],
  vi:[["Daily Standup","reunión diaria"],["sprint / backlog","sprint / pila"],["blocker","bloqueo"],["to be blocked by…","estar bloqueado por…"],["work in progress (WIP)","trabajo en curso"],["to prioritize","priorizar"],["deadline","fecha límite"],["done / in review","hecho / en revisión"],["stakeholder","interesado"],["retrospective","retrospectiva"]],
  gr:["Present Perfect (have/has + participio)","for / since / already / yet","be going to (planes)"],
  ph:["Yesterday I closed three tickets; today I'm going to work on the network issue.","I'm blocked by the access request, so I need help."]},
 {code:"M8",from:"B1",to:"B2",title:"Escalado · Comunicación compleja",
  og:["Hacer sugerencias e hipótesis","Escribir emails formales","Peticiones indirectas"],
  oi:["Escalar una incidencia a nivel 2/3","Redactar informes y SLAs"],
  vg:[["I would suggest…","Yo sugeriría…"],["If I were you…","Yo que tú…"],["I'm writing to…","Le escribo para…"],["Please find attached…","Adjunto…"]],
  vi:[["to escalate","escalar"],["to assign / reassign","asignar / reasignar"],["priority (high/low)","prioridad"],["SLA","acuerdo de nivel de servicio"],["incident report","informe de incidencia"],["workaround","solución temporal"],["known issue","problema conocido"],["to follow up","dar seguimiento"],["on-call","de guardia"],["ASAP","cuanto antes"]],
  gr:["First conditional (if + present, will)","Estilo indirecto básico","make / let / allow"],
  ph:["If the issue isn't fixed today, we will escalate it to level 2.","I would suggest a temporary workaround while we investigate."]},
 {code:"M9",from:"B2",to:"B2",title:"Automatización · Scripts y despliegue",
  og:["Explicar procesos y causa-efecto","Cláusulas de relativo","Hipótesis (second conditional)"],
  oi:["Automatización de tareas y scripting","Despliegue de servidores locales / CI-CD"],
  vg:[["because of / due to","debido a"],["which / that / who","que / quien"],["If I had…, I would…","Si tuviera…, haría…"],["as a result","como resultado"]],
  vi:[["to automate","automatizar"],["script","script"],["scheduled task / cron job","tarea programada"],["to deploy","desplegar"],["local server","servidor local"],["virtual machine (VM)","máquina virtual"],["container","contenedor"],["pipeline (CI/CD)","tubería CI/CD"],["backup","copia de seguridad"],["to trigger","desencadenar"]],
  gr:["Cláusulas de relativo","Second conditional","so / such / because of"],
  ph:["We use a script that automatically backs up the database every night.","If we automated this task, we would save two hours a day."]},
 {code:"M10",from:"B2",to:"B2",title:"Vanguardia · IA, agentes y domótica",
  og:["Hablar del futuro y de tendencias","Modales de probabilidad","Opinar sobre tecnología"],
  oi:["Vocabulario de agentes de IA y prompts","IoT y domótica (smart home)"],
  vg:[["will / won't","(no) sucederá"],["might / may","podría / puede que"],["I reckon…","Yo creo…"],["It's likely that…","Es probable que…"]],
  vi:[["AI agent","agente de IA"],["prompt","instrucción / prompt"],["to fine-tune","ajustar / afinar"],["machine learning","aprendizaje automático"],["smart home","hogar inteligente"],["sensor","sensor"],["IoT device","dispositivo IoT"],["to integrate","integrar"],["voice assistant","asistente de voz"],["to trigger a routine","activar una rutina"]],
  gr:["Formas de futuro (will / going to / present cont.)","Modales de probabilidad (might, must, can't)","used to / would (hábitos)"],
  ph:["This AI agent might handle the first level of support in the future.","When the sensor detects motion, it triggers a routine that turns on the lights."]},
 {code:"M11",from:"B2",to:"B2",title:"Profesional · Entrevista y fluidez",
  og:["Entrevista de trabajo (método STAR)","Hablar de fortalezas y logros","Conectores del discurso"],
  oi:["Describir tu experiencia como técnico junior","Responder preguntas técnicas con seguridad"],
  vg:[["My strengths are…","Mis fortalezas son…"],["I'm good at…","Se me da bien…"],["For example / However","Por ejemplo / Sin embargo"],["To sum up","En resumen"]],
  vi:[["experience / background","experiencia / formación"],["to troubleshoot","diagnosticar y resolver"],["hands-on experience","experiencia práctica"],["to be responsible for…","ser responsable de…"],["achievement","logro"],["team player","persona de equipo"],["to handle pressure","gestionar la presión"],["available to start","disponible para empezar"],["notice period","preaviso"],["salary expectations","expectativas salariales"]],
  gr:["Repaso general de tiempos verbales","Phrasal verbs frecuentes en IT","Marcadores del discurso"],
  ph:["I have hands-on experience troubleshooting Windows and Linux systems.","In my last role I was responsible for the first level of support."]},
 {code:"M12",from:"C1",to:"C1",title:"Ciberseguridad · Zero Trust",
  og:["Redactar políticas y directrices","Explicar riesgos complejos","Persuadir sobre buenas prácticas"],
  oi:["Conceptos avanzados de ciberseguridad","Mitigación de vulnerabilidades y auditoría"],
  vg:[["to emphasize","enfatizar"],["crucial / paramount","crucial / primordial"],["to comply with","cumplir con"],["framework","marco de trabajo"]],
  vi:[["Zero Trust","confianza cero"],["vulnerability assessment","evaluación de vulnerabilidades"],["phishing / spear-phishing","suplantación de identidad"],["penetration testing","prueba de penetración"],["to encrypt / decrypt","cifrar / descifrar"],["data breach","brecha de datos"],["threat actor","actor de amenaza"],["multi-factor authentication (MFA)","autenticación multifactor"],["patch management","gestión de parches"],["compliance","cumplimiento normativo"]],
  gr:["Voz pasiva avanzada","Condicionales mixtos","Inversión para énfasis (Rarely do we...)"],
  ph:["Under no circumstances should the encryption keys be shared.","If the patch had been applied, the breach wouldn't have happened."]},
 {code:"M13",from:"C1",to:"C1",title:"Cloud · Arquitectura y AWS/Azure",
  og:["Comparar costes y beneficios","Describir infraestructuras complejas","Hablar de escalabilidad"],
  oi:["Servicios en la nube (IaaS, PaaS, SaaS)","Migraciones al cloud y alta disponibilidad"],
  vg:[["cost-effective","rentable"],["on-demand","bajo demanda"],["seamlessly","sin problemas / fluidamente"],["to scale up / down","escalar (aumentar/reducir)"]],
  vi:[["cloud computing","computación en la nube"],["virtual private cloud (VPC)","nube privada virtual"],["high availability","alta disponibilidad"],["load balancer","balanceador de carga"],["auto-scaling group","grupo de autoescalado"],["serverless","sin servidor"],["data residency","residencia de datos"],["latency optimization","optimización de latencia"],["vendor lock-in","dependencia del proveedor"],["disaster recovery","recuperación ante desastres"]],
  gr:["Estructuras comparativas avanzadas (the more... the more...)","Participios de relativo","Conectores de concesión (despite, although)"],
  ph:["The more traffic we receive, the more instances are spun up automatically.","Despite the initial costs, migrating to PaaS is highly cost-effective."]},
 {code:"M14",from:"C1",to:"C1",title:"DevOps · SRE y Pipelines",
  og:["Debatir sobre cultura organizacional","Métricas y rendimientos","Explicar flujos de trabajo (workflows)"],
  oi:["Integración y despliegue continuo (CI/CD)","Monitorización y Site Reliability Engineering"],
  vg:[["mindset","mentalidad"],["bottleneck","cuello de botella"],["to streamline","optimizar / agilizar"],["throughput","rendimiento / capacidad"]],
  vi:[["continuous integration (CI)","integración continua"],["continuous deployment (CD)","despliegue continuo"],["infrastructure as code (IaC)","infraestructura como código"],["version control","control de versiones"],["observability","observabilidad"],["telemetry","telemetría"],["service level objective (SLO)","objetivo de nivel de servicio"],["error budget","presupuesto de errores"],["microservices","microservicios"],["container orchestration","orquestación de contenedores"]],
  gr:["Uso de gerundios como sujetos","Verbos con doble objeto","Phrasal verbs idiomáticos"],
  ph:["Streamlining the CI/CD pipeline drastically reduced our time-to-market.","We have exhausted our error budget for this quarter."]},
 {code:"M15",from:"C1",to:"C1",title:"Liderazgo · Soft Skills IT",
  og:["Dar y recibir feedback constructivo","Negociación y resolución de conflictos","Liderar reuniones técnicas"],
  oi:["Mentoring de perfiles junior","Gestión de stakeholders no técnicos"],
  vg:[["to point out","señalar / destacar"],["to compromise","llegar a un acuerdo"],["to micromanage","microgestionar"],["big picture","visión general"]],
  vi:[["to mentor","ser mentor / guiar"],["knowledge transfer","transferencia de conocimientos"],["technical debt","deuda técnica"],["onboarding","integración de nuevos empleados"],["burnout","agotamiento profesional"],["cross-functional team","equipo multifuncional"],["proof of concept (PoC)","prueba de concepto"],["return on investment (ROI)","retorno de inversión"],["scope creep","descontrol del alcance"],["milestone","hito"]],
  gr:["Modales de deducción en pasado (must have, might have)","Discurso reportado avanzado","Adjetivos compuestos"],
  ph:["We must have misunderstood the stakeholder's requirements regarding the UI.","Addressing technical debt is crucial to avoid scope creep later on."]}
];

export const CATS = {
  helpdesk:{label:"Helpdesk",color:"var(--amber)"}, networks:{label:"Redes",color:"var(--teal)"},
  systems:{label:"Sistemas",color:"var(--teal)"}, agile:{label:"Ágiles",color:"var(--amber)"},
  tech:{label:"Vanguardia",color:"var(--teal)"}, life:{label:"Vida real",color:"var(--amber)"},
  interview:{label:"Entrevista",color:"var(--coral)"},
};

export const SCENARIOS = [
 {id:"s-pc",cat:"helpdesk",level:"A2",title:"El PC no enciende",role:"Eres el técnico. Un usuario llama porque su ordenador no arranca.",persona:"Interpretas a Sarah, usuaria de oficina, poco técnica y algo nerviosa. Su ordenador no enciende. En realidad el cable de corriente está flojo, pero no lo sabes hasta que el técnico te guíe a comprobarlo. Empieza tú describiendo el problema."},
 {id:"s-pass",cat:"helpdesk",level:"A2",title:"Contraseña bloqueada",role:"Eres el técnico. Un usuario no puede iniciar sesión: cuenta bloqueada.",persona:"Interpretas a Tom, comercial que ha olvidado su contraseña y su cuenta se ha bloqueado tras varios intentos. Necesitas volver a entrar para una reunión. Empieza tú explicando la urgencia."},
 {id:"s-slow",cat:"helpdesk",level:"B1",title:"El equipo va muy lento",role:"Eres el técnico. El usuario se queja de que todo va lentísimo.",persona:"Interpretas a Marta, de contabilidad. El portátil va muy lento y se congela al abrir varias aplicaciones. Tiene muchas pestañas y programas abiertos. Empieza tú describiendo los síntomas."},
 {id:"s-print",cat:"helpdesk",level:"B1",title:"La impresora de red no imprime",role:"Eres el técnico. Nadie de la planta puede imprimir.",persona:"Interpretas a David, de recepción. La impresora de red no responde y toda la planta está afectada. Otros compañeros también se quejan. Empieza tú reportando el problema."},
 {id:"s-net",cat:"networks",level:"B1",title:"Sin conexión a internet",role:"Eres el técnico. Un usuario se ha quedado sin red.",persona:"Interpretas a Lucía, en teletrabajo por VPN. De repente ha perdido la conexión. El icono de wifi aparece con un aviso. Empieza tú describiendo qué ves en pantalla."},
 {id:"s-linux",cat:"systems",level:"B1",title:"Permisos en Linux",role:"Eres el técnico. Guías a un compañero por la terminal de Linux.",persona:"Interpretas a Pablo, desarrollador junior que no puede ejecutar un script: recibe 'Permission denied'. Sabe algo de terminal pero necesita ayuda con permisos. Empieza tú explicando el error que ves."},
 {id:"s-daily",cat:"agile",level:"B1",title:"Daily Standup",role:"Participas en la reunión diaria del equipo de soporte. TÚ eres el técnico junior que reporta.",persona:"Interpretas a Elena, la Scrum Master del equipo de soporte IT. Diriges el Daily Standup y pides al alumno que responda: qué hizo ayer, qué hará hoy y si tiene bloqueos. Empieza tú saludando y dando paso."},
 {id:"s-esc",cat:"agile",level:"B2",title:"Escalar a nivel 2",role:"Eres el técnico de nivel 1. Debes escalar una incidencia a un compañero senior.",persona:"Interpretas a Robert, técnico senior de nivel 2. El alumno (nivel 1) tiene que explicarte una incidencia que no puede resolver y convencerte de que la tomes. Pregunta qué pasos ha probado, prioridad e impacto. Empieza tú preguntando qué necesita."},
 {id:"s-ai",cat:"tech",level:"B2",title:"Presentar una automatización",role:"Presentas a tu responsable una idea para automatizar tareas con un agente de IA.",persona:"Interpretas a Nadia, responsable de operaciones. El alumno quiere proponerte automatizar la clasificación de tickets con un agente de IA. Eres receptiva pero exigente: pregunta por beneficios, riesgos y coste. Empieza tú preguntándole qué propone."},
 {id:"s-cafe",cat:"life",level:"A2",title:"Un café en el trabajo",role:"Charla informal con un compañero nuevo en la cafetería.",persona:"Interpretas a Jake, compañero nuevo de otro equipo. Es la hora del café y charláis relajados: de dónde sois, qué hacéis, planes de finde. Mantén el nivel sencillo y amable. Empieza tú presentándote."},
 {id:"s-air",cat:"life",level:"B1",title:"Check-in en el aeropuerto",role:"Vas a un congreso de tecnología. Facturas en el mostrador.",persona:"Interpretas al agente de facturación de una aerolínea. El alumno viaja a una conferencia de IT. Gestiona tarjeta de embarque, equipaje y asiento, y haz las preguntas de seguridad habituales. Empieza tú saludando y pidiendo el pasaporte."},
 {id:"s-int",cat:"interview",level:"B2",title:"Entrevista: Técnico Junior de Sistemas",role:"Entrevista de trabajo en inglés para IT Support / Junior Systems.",persona:"Interpretas a Karen, IT Manager que entrevista al alumno para Técnico Junior de Sistemas / Helpdesk. Preguntas realistas: preséntate, experiencia con Windows/Linux, cómo resuelves una incidencia, trabajo en equipo, disponibilidad. Una pregunta cada vez. Empieza tú dando la bienvenida y pidiendo que se presente."},
];

/* reading bank */
export const READING = [
 {id:"r1",level:"A2",cat:"life",title:"A New Work Laptop",
  text:"Hi, I'm Elena and I work in an office in Madrid. This week my company gave me a new laptop. It is light and fast, and the screen is bigger than my old one. In the morning I turn it on, I log in with my password, and I check my emails. I like it a lot, but the keyboard is a little different, so sometimes I make mistakes when I type.",
  qs:[
   {q:"Where does Elena work?",opts:["In an office in Madrid","In a shop","At home","In a school"],a:0,ex:"“I work in an office in Madrid.”"},
   {q:"What is new?",opts:["Her laptop","Her phone","Her desk","Her car"],a:0,ex:"“my company gave me a new laptop.”"},
   {q:"The new screen is ___ than the old one.",opts:["bigger","smaller","older","darker"],a:0,ex:"“the screen is bigger than my old one.”"},
   {q:"Why does she sometimes make mistakes?",opts:["The keyboard is a little different","The laptop is slow","The screen is small","She is tired"],a:0,ex:"“the keyboard is a little different, so sometimes I make mistakes.”"}]},
 {id:"r2",level:"A2",cat:"helpdesk",title:"A Support Email",
  text:"Subject: My computer is very slow.\n\nHello IT team,\nSince yesterday my computer has been very slow. It takes five minutes to open a program, and sometimes the screen freezes. I have restarted it twice, but the problem is still there. I have an important meeting at 3 p.m., so I need help soon.\nThank you,\nDavid (Sales department)",
  qs:[
   {q:"When did the problem start?",opts:["Yesterday","Last week","This morning","Two hours ago"],a:0,ex:"“Since yesterday my computer has been very slow.”"},
   {q:"What happens sometimes?",opts:["The screen freezes","The computer turns off","The internet stops","The printer breaks"],a:0,ex:"“sometimes the screen freezes.”"},
   {q:"What has David already tried?",opts:["Restarting the computer","Calling a colleague","Buying a new PC","Updating Windows"],a:0,ex:"“I have restarted it twice.”"},
   {q:"Why does he need help soon?",opts:["He has a meeting at 3 p.m.","He wants to go home","His boss is angry","He is on holiday"],a:0,ex:"“I have an important meeting at 3 p.m.”"}]},
 {id:"r3",level:"B1",cat:"networks",title:"Restarting the Router",
  text:"If you lose your internet connection at home, restarting the router often solves the problem. First, unplug the router from the power and wait about thirty seconds. Then plug it back in and wait for the lights to become stable — this can take two or three minutes. When the connection light is green, try to open a website. If you still have no internet after this, the problem may be with your provider, so you should contact their support team.",
  qs:[
   {q:"What should you do first?",opts:["Unplug the router","Call the provider","Open a website","Change the cable"],a:0,ex:"“First, unplug the router from the power.”"},
   {q:"How long should you wait before plugging it back in?",opts:["About thirty seconds","Five minutes","One hour","Ten seconds"],a:0,ex:"“wait about thirty seconds.”"},
   {q:"What does a green connection light mean?",opts:["The connection is ready","There is no internet","The router is broken","You must wait more"],a:0,ex:"“When the connection light is green, try to open a website.”"},
   {q:"If there is still no internet, who should you contact?",opts:["Your provider's support team","A friend","The police","Nobody"],a:0,ex:"“you should contact their support team.”"}]},
 {id:"r4",level:"B1",cat:"life",title:"A Weekend in Lisbon",
  text:"Last weekend I travelled to Lisbon with two friends. We arrived on Friday evening and took a taxi to our hotel in the city centre. On Saturday we walked around the old town, tried some local food, and visited a famous castle with great views. The weather was warm and sunny. On Sunday morning we did some shopping before our flight home. It was a short trip, but we really enjoyed it and we want to go back next year.",
  qs:[
   {q:"Who did the writer travel with?",opts:["Two friends","Their family","Alone","Colleagues"],a:0,ex:"“I travelled to Lisbon with two friends.”"},
   {q:"When did they arrive?",opts:["Friday evening","Saturday morning","Sunday","Thursday night"],a:0,ex:"“We arrived on Friday evening.”"},
   {q:"What did they visit on Saturday?",opts:["A castle","A museum","A beach","A stadium"],a:0,ex:"“visited a famous castle with great views.”"},
   {q:"How was the weather?",opts:["Warm and sunny","Cold and rainy","Windy","Foggy"],a:0,ex:"“The weather was warm and sunny.”"},
   {q:"What do they want to do?",opts:["Go back next year","Move to Lisbon","Never return","Stay longer"],a:0,ex:"“we want to go back next year.”"}]},
 {id:"r5",level:"B2",cat:"systems",title:"Incident Report: Server Outage",
  text:"At 14:20 on Monday, the main application server went down and around 200 users lost access to the internal system. The on-call engineer checked the logs and discovered that the disk was completely full because of an old backup process that had not been cleaned up. As a temporary workaround, the team deleted the outdated backup files, which restored the service within twenty minutes. To prevent this from happening again, the team scheduled an automated task to remove old backups every night and added an alert that triggers when disk usage goes above 80%.",
  qs:[
   {q:"How many users were affected?",opts:["About 200","About 20","About 2,000","Only a few"],a:0,ex:"“around 200 users lost access.”"},
   {q:"What was the root cause?",opts:["The disk was full","A power cut","A network attack","A software update"],a:0,ex:"“the disk was completely full because of an old backup process.”"},
   {q:"What was the temporary workaround?",opts:["Deleting outdated backup files","Restarting the server","Buying a new disk","Calling the provider"],a:0,ex:"“the team deleted the outdated backup files.”"},
   {q:"What will the new alert do?",opts:["Trigger when disk usage is above 80%","Send a daily report","Restart the server","Block new users"],a:0,ex:"“an alert that triggers when disk usage goes above 80%.”"},
   {q:"What is the purpose of the scheduled task?",opts:["To remove old backups every night","To create more backups","To update the system","To add users"],a:0,ex:"“an automated task to remove old backups every night.”"}]},
 {id:"r6",level:"B2",cat:"tech",title:"Getting Started with a Smart Home",
  text:"A smart home lets you control devices such as lights, heating, and cameras from your phone or with your voice. Most systems use a central hub that connects to your Wi-Fi and communicates with sensors around the house. For example, a motion sensor can detect when you enter a room and automatically turn on the lights. You can also create routines: when you say 'good night', the system might lock the doors, turn off the lights, and lower the heating at the same time. However, because these devices are connected to the internet, it is important to use strong passwords and keep the software updated to avoid security risks.",
  qs:[
   {q:"How can you control a smart home?",opts:["From your phone or with your voice","Only with a remote","Only from a computer","With a key"],a:0,ex:"“from your phone or with your voice.”"},
   {q:"What does the central hub connect to?",opts:["Your Wi-Fi","The television","A printer","The car"],a:0,ex:"“a central hub that connects to your Wi-Fi.”"},
   {q:"What can a motion sensor do?",opts:["Turn on the lights when you enter","Lock the car","Play music","Send emails"],a:0,ex:"“a motion sensor can detect when you enter a room and automatically turn on the lights.”"},
   {q:"What might happen when you say 'good night'?",opts:["Doors lock, lights off, heating lower","The alarm rings","The TV turns on","Nothing"],a:0,ex:"“lock the doors, turn off the lights, and lower the heating.”"},
   {q:"Why is security important?",opts:["Devices are connected to the internet","They use batteries","They are expensive","They are big"],a:0,ex:"“because these devices are connected to the internet.”"}]},
 {id:"r7",level:"C1",cat:"tech",title:"Zero Trust Architecture Explained",
  text:"In the modern cybersecurity landscape, the traditional perimeter defense model is obsolete. Enter Zero Trust Architecture (ZTA). The core tenet of ZTA is 'never trust, always verify'. Unlike legacy systems that grant broad access once a user is inside the corporate network, Zero Trust assumes that threats exist both outside and inside the network boundaries. Therefore, every request to access a resource must be strictly authenticated and authorized, regardless of where the request originates. This approach relies heavily on micro-segmentation, continuous monitoring, and multi-factor authentication (MFA). Implementing ZTA is not just about adopting new tools; it requires a fundamental shift in organizational mindset and security culture.",
  qs:[
   {q:"What is the core tenet of Zero Trust?",opts:["Never trust, always verify","Trust but verify","Trust everyone inside","Verify only external users"],a:0,ex:"“The core tenet of ZTA is 'never trust, always verify'.”"},
   {q:"How does Zero Trust view the corporate network?",opts:["It assumes threats exist inside and outside","It considers it a safe zone","It ignores internal threats","It focuses only on the perimeter"],a:0,ex:"“Zero Trust assumes that threats exist both outside and inside the network boundaries.”"},
   {q:"What is required for every resource request in ZTA?",opts:["Strict authentication and authorization","A fast internet connection","A VPN","Manager approval"],a:0,ex:"“every request to access a resource must be strictly authenticated and authorized.”"},
   {q:"Which of the following is a key technology for ZTA?",opts:["Micro-segmentation","Legacy systems","Broad access policies","Antivirus software"],a:0,ex:"“This approach relies heavily on micro-segmentation...”"},
   {q:"What kind of shift does implementing ZTA require?",opts:["A shift in mindset and security culture","Buying faster computers","Hiring more staff","Moving to a new office"],a:0,ex:"“it requires a fundamental shift in organizational mindset and security culture.”"}]},
 {id:"r8",level:"C1",cat:"systems",title:"Post-Mortem: Database Failover",
  text:"Executive Summary: On October 12th, our primary PostgreSQL cluster experienced a split-brain scenario during a routine automated failover test, leading to 45 minutes of degraded performance and a brief data inconsistency window. \n\nRoot Cause Analysis: The underlying issue was traced back to a misconfiguration in the high-availability (HA) proxy heartbeats. A temporary network partition caused the secondary node to prematurely assume the primary role while the original primary was still accepting writes. \n\nResolution & Next Steps: The SRE team manually demoted the rogue primary and initiated a partial state sync to reconcile the delta. To mitigate future occurrences, we are overhauling the consensus algorithm configuration (moving to a more robust Quorum-based approach) and implementing stricter fencing mechanisms (STONITH) to reliably power off unresponsive nodes before promotion.",
  qs:[
   {q:"What caused the split-brain scenario?",opts:["A misconfiguration in HA proxy heartbeats","A power outage","A cyberattack","A full hard drive"],a:0,ex:"“The underlying issue was traced back to a misconfiguration in the high-availability (HA) proxy heartbeats.”"},
   {q:"What did the secondary node do during the network partition?",opts:["It prematurely assumed the primary role","It shut down","It deleted data","It contacted support"],a:0,ex:"“the secondary node to prematurely assume the primary role...”"},
   {q:"How did the SRE team resolve the immediate issue?",opts:["Manually demoted the rogue primary and synced state","Restarted the servers","Restored from yesterday's backup","Ignored it"],a:0,ex:"“The SRE team manually demoted the rogue primary and initiated a partial state sync...”"},
   {q:"What consensus approach are they moving to?",opts:["A Quorum-based approach","A Master-Slave approach","A random approach","No consensus"],a:0,ex:"“moving to a more robust Quorum-based approach.”"},
   {q:"What is the purpose of STONITH in this context?",opts:["To reliably power off unresponsive nodes","To speed up the database","To encrypt data","To monitor traffic"],a:0,ex:"“implementing stricter fencing mechanisms (STONITH) to reliably power off unresponsive nodes...”"}]}
];

/* listening bank (TTS reads the lines) */
export const LISTENING = [
 {id:"l1",level:"A2",cat:"life",title:"Coffee Break",
  lines:[
   {who:"Jake",text:"Hi, I'm Jake. I just started in the marketing team. Are you new here too?"},
   {who:"You",text:"Hello Jake, nice to meet you. I'm on the IT support team. I started three weeks ago."},
   {who:"Jake",text:"Oh, great. This coffee machine is a bit complicated. How do you like the job so far?"},
   {who:"You",text:"I like it a lot. The people are friendly and I'm learning new things every day."},
   {who:"Jake",text:"That's good to hear. Do you have any plans for the weekend?"},
   {who:"You",text:"Yes, I'm going to visit my family and play some football on Sunday."}],
  qs:[
   {q:"Which team is Jake on?",opts:["Marketing","IT support","Sales","Finance"],a:0,ex:"“I just started in the marketing team.”"},
   {q:"How long has the other person worked here?",opts:["Three weeks","Three days","Three months","One year"],a:0,ex:"“I started three weeks ago.”"},
   {q:"What does the person think about the job?",opts:["They like it a lot","It is boring","It is too hard","They want to leave"],a:0,ex:"“I like it a lot.”"},
   {q:"What are their weekend plans?",opts:["Visit family and play football","Work","Travel abroad","Study"],a:0,ex:"“visit my family and play some football on Sunday.”"}]},
 {id:"l2",level:"B1",cat:"helpdesk",title:"A Support Call",
  lines:[
   {who:"Agent",text:"Good morning, IT helpdesk, this is Sarah speaking. How can I help you?"},
   {who:"Caller",text:"Hi, I can't log in to my computer. It says my password is incorrect, but I'm sure it's the right one."},
   {who:"Agent",text:"Okay, don't worry. Can you tell me your username, please?"},
   {who:"Caller",text:"Yes, it's d dot martin."},
   {who:"Agent",text:"Thank you. I can see your account is locked because of too many attempts. I'll reset it now. Please try again in two minutes."},
   {who:"Caller",text:"Perfect, thank you very much."}],
  qs:[
   {q:"What is the caller's problem?",opts:["They can't log in","The internet is down","The printer is broken","The screen is black"],a:0,ex:"“I can't log in to my computer.”"},
   {q:"Why is the account locked?",opts:["Too many login attempts","A virus","An update","A power cut"],a:0,ex:"“your account is locked because of too many attempts.”"},
   {q:"What will the agent do?",opts:["Reset the account","Send a new computer","Call the manager","Close the ticket"],a:0,ex:"“I'll reset it now.”"},
   {q:"When should the caller try again?",opts:["In two minutes","Tomorrow","In one hour","Immediately"],a:0,ex:"“Please try again in two minutes.”"}]},
 {id:"l3",level:"B1",cat:"agile",title:"Daily Standup",
  lines:[
   {who:"Elena",text:"Good morning everyone, let's start the daily standup. Tom, can you begin? What did you do yesterday?"},
   {who:"Tom",text:"Yesterday I closed three support tickets and I finished the network documentation. Today I'm going to work on the printer issue on the second floor. I don't have any blockers."},
   {who:"Elena",text:"Great, thank you. Remember we have the sprint review on Friday, so please update your tasks on the board."}],
  qs:[
   {q:"What did Tom do yesterday?",opts:["Closed tickets and finished documentation","Went on holiday","Fixed the printer","Nothing"],a:0,ex:"“I closed three support tickets and I finished the network documentation.”"},
   {q:"What will Tom do today?",opts:["Work on the printer issue","Write emails","Attend a meeting","Install servers"],a:0,ex:"“Today I'm going to work on the printer issue.”"},
   {q:"Does Tom have any blockers?",opts:["No","Yes, one","Yes, two","He didn't say"],a:0,ex:"“I don't have any blockers.”"},
   {q:"When is the sprint review?",opts:["Friday","Monday","Wednesday","Today"],a:0,ex:"“we have the sprint review on Friday.”"}]},
 {id:"l4",level:"B2",cat:"tech",title:"Automation Announcement",
  lines:[
   {who:"Nadia",text:"Hi team, I want to share some news about our support process. Starting next month, we're going to introduce an AI agent that will automatically classify incoming tickets by priority and topic. This should save us a lot of time on repetitive tasks and let us focus on the more complex issues. Of course, every ticket will still be reviewed by a person, so nothing will be closed automatically. We'll run a two-week trial first, and I'd really appreciate your feedback during that period."}],
  qs:[
   {q:"What will the AI agent do?",opts:["Classify tickets by priority and topic","Reply to customers","Delete old tickets","Reset passwords"],a:0,ex:"“classify incoming tickets by priority and topic.”"},
   {q:"When will it start?",opts:["Next month","Today","Next year","Next week"],a:0,ex:"“Starting next month…”"},
   {q:"Will tickets be closed automatically?",opts:["No, a person reviews them","Yes, all of them","Only urgent ones","Yes, at night"],a:0,ex:"“every ticket will still be reviewed by a person, so nothing will be closed automatically.”"},
   {q:"How long is the trial period?",opts:["Two weeks","One month","Two days","Six months"],a:0,ex:"“We'll run a two-week trial first.”"}]},
 {id:"l5",level:"C1",cat:"agile",title:"Cloud Migration Planning",
  lines:[
   {who:"Architect",text:"Alright team, let's discuss the upcoming migration from our on-premise datacenter to AWS. We need to finalize the strategy. Are we going with a lift-and-shift approach, or should we refactor the monolithic app into microservices right away?"},
   {who:"Lead Dev",text:"If we refactor now, it's going to significantly delay the timeline. The technical debt in the legacy codebase is massive. I strongly advocate for a lift-and-shift first to get us out of the datacenter, and then we can modernize incrementally."},
   {who:"Architect",text:"That's a valid point. However, lifting and shifting a monolithic architecture might lead to huge compute costs if we can't utilize auto-scaling properly. What does the DevOps team think?"},
   {who:"DevOps",text:"I agree with the Lead Dev. We can use containerization to encapsulate the monolith, deploy it on EKS, and then slowly strangle the monolith by breaking off microservices over the next few quarters. It's the safest bet."}],
  qs:[
   {q:"What is the main topic of the meeting?",opts:["Migrating from on-premise to AWS","Buying new servers","Hiring a new developer","Updating Windows"],a:0,ex:"“let's discuss the upcoming migration from our on-premise datacenter to AWS.”"},
   {q:"Why does the Lead Dev oppose refactoring right away?",opts:["It will delay the timeline due to technical debt","It is too expensive","They don't know how","AWS doesn't support it"],a:0,ex:"“If we refactor now, it's going to significantly delay the timeline. The technical debt in the legacy codebase is massive.”"},
   {q:"What is the Architect's concern about lift-and-shift?",opts:["Huge compute costs without auto-scaling","It is too slow","It is not secure","It requires too much code"],a:0,ex:"“lifting and shifting a monolithic architecture might lead to huge compute costs if we can't utilize auto-scaling properly.”"},
   {q:"What strategy does the DevOps engineer propose?",opts:["Containerize the monolith and modernize incrementally","Rewrite everything immediately","Stay on-premise","Move to Azure instead"],a:0,ex:"“containerization to encapsulate the monolith... and then slowly strangle the monolith by breaking off microservices.”"}]},
 {id:"l6",level:"C1",cat:"networks",title:"Security Breach Escalation",
  lines:[
   {who:"Analyst",text:"We've got a critical alert. I'm seeing anomalous outbound traffic from the HR database server to an unknown IP address located overseas. It looks like data exfiltration."},
   {who:"Manager",text:"Are you sure? Could it be a scheduled backup or an API integration?"},
   {who:"Analyst",text:"Negative. I checked the logs and the traffic bypasses our standard proxy. Furthermore, the payload is heavily encrypted, which matches the signature of a known ransomware group. We need to isolate that VLAN immediately."},
   {who:"Manager",text:"Okay, initiate the incident response protocol. Cut off external access to that subnet, but keep the server running so the forensics team can take a memory dump. I'll notify the legal team and the CISO."}],
  qs:[
   {q:"What issue has the Analyst detected?",opts:["Anomalous outbound traffic from the HR database","A broken router","A slow internet connection","A forgotten password"],a:0,ex:"“I'm seeing anomalous outbound traffic from the HR database server...”"},
   {q:"What did the Manager initially think it might be?",opts:["A scheduled backup or API integration","A hardware failure","A user mistake","A power outage"],a:0,ex:"“Could it be a scheduled backup or an API integration?”"},
   {q:"Why does the Analyst believe it is ransomware?",opts:["The payload is encrypted and matches a known signature","They received a ransom email","The screen is locked","A user told them"],a:0,ex:"“the payload is heavily encrypted, which matches the signature of a known ransomware group.”"},
   {q:"What is the immediate action taken?",opts:["Initiate incident response and isolate the VLAN","Delete the database","Shut down the server","Pay the ransom"],a:0,ex:"“initiate the incident response protocol. Cut off external access to that subnet...”"}]}
];

export const DICTATION = [
 "Please restart your computer.",
 "The server has been down since this morning.",
 "I can't connect to the wireless network.",
 "Could you open a ticket for this issue?",
 "We need to update the operating system tonight.",
 "The printer on the second floor is not working.",
 "Let's automate this task with a script.",
 "I'll follow up with you after the meeting.",
];

export const WRITING = [
  {id:"w1",level:"A2",cat:"helpdesk",title:"Ticket Update",
   prompt:"Write a short email to a user (David) telling him that his password has been reset. Tell him his new temporary password is 'Temp1234!' and ask him to log in and change it.",
   hint:"Dear David, Your password has been reset..."},
  {id:"w2",level:"B1",cat:"networks",title:"Network Outage Notice",
   prompt:"Write a notice to all staff about a planned network outage this Friday at 10 PM. It will last for two hours. Apologize for the inconvenience.",
   hint:"Subject: Planned Network Outage. Dear team, Please be advised..."},
  {id:"w3",level:"B2",cat:"agile",title:"Daily Status Update",
   prompt:"Write a Slack message to your team for the Daily Standup. State what you did yesterday (fixed the login bug), what you will do today (start the database migration), and mention a blocker (waiting for API keys from the DevOps team).",
   hint:"Hi team, yesterday I fixed... today I am going to... My blocker is..."},
  {id:"w4",level:"C1",cat:"systems",title:"Incident Escalation",
   prompt:"Draft an urgent email to the Level 3 Support Team. Escalate an issue where the main payment gateway API is throwing 500 Internal Server Errors. Mention that Level 1 and 2 have already checked the logs and found a timeout issue with the external provider. Request immediate assistance.",
   hint:"Hi L3 Team, I am escalating a critical incident regarding..."}
];

export const SPEAKING = [
  {id:"sp1",level:"A2",cat:"life",title:"Introducing Yourself",
   prompt:"You are meeting a new colleague. Introduce yourself, state your role (Junior IT Support), and ask them what department they work in.",
   checklist:["Said 'Hello' or 'Hi'","Stated your name","Mentioned your role in IT","Asked about their department"]},
  {id:"sp2",level:"B1",cat:"helpdesk",title:"Guiding a User",
   prompt:"A user's computer is frozen. Tell them step-by-step to hold the power button for 10 seconds to force a shutdown, wait a few seconds, and turn it back on.",
   checklist:["Used clear imperatives (e.g., 'Please hold...')","Mentioned the power button","Specified 10 seconds","Instructed to turn it back on"]},
  {id:"sp3",level:"B2",cat:"interview",title:"Explaining a Concept",
   prompt:"An interviewer asks you: 'Can you explain in simple terms what a VPN is and why we use it?' Give a 30-second answer.",
   checklist:["Defined VPN (Virtual Private Network)","Explained it creates a secure/encrypted tunnel","Mentioned remote access or security","Kept it simple and clear"]},
  {id:"sp4",level:"C1",cat:"tech",title:"Proposing a Solution",
   prompt:"In a meeting, propose migrating an old on-premise application to AWS. Mention benefits like scalability and high availability, but also acknowledge the initial setup cost.",
   checklist:["Proposed the AWS migration clearly","Mentioned 'scalability'","Mentioned 'high availability'","Acknowledged the 'setup cost' or 'initial cost'"]}
];