services:
  app-generator-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY:-}
        - VITE_GEMINI_API_KEY_2=${VITE_GEMINI_API_KEY_2:-}
        - VITE_GEMINI_API_KEY_3=${VITE_GEMINI_API_KEY_3:-}
        - VITE_GEMINI_API_KEY_4=${VITE_GEMINI_API_KEY_4:-}
        - VITE_GEMINI_API_KEY_5=${VITE_GEMINI_API_KEY_5:-}
        - VITE_GEMINI_API_KEY_6=${VITE_GEMINI_API_KEY_6:-}
        - VITE_GEMINI_API_KEY_7=${VITE_GEMINI_API_KEY_7:-}
        - VITE_GEMINI_API_KEY_8=${VITE_GEMINI_API_KEY_8:-}
        - VITE_GEMINI_API_KEY_9=${VITE_GEMINI_API_KEY_9:-}
        - VITE_GEMINI_API_KEY_10=${VITE_GEMINI_API_KEY_10:-}
        - VITE_GEMINI_API_KEY_11=${VITE_GEMINI_API_KEY_11:-}
        - VITE_GEMINI_API_KEY_12=${VITE_GEMINI_API_KEY_12:-}
        - VITE_GEMINI_API_KEY_13=${VITE_GEMINI_API_KEY_13:-}
        - VITE_GEMINI_API_KEY_14=${VITE_GEMINI_API_KEY_14:-}
        - VITE_GEMINI_API_KEY_15=${VITE_GEMINI_API_KEY_15:-}
        - VITE_GEMINI_API_KEY_16=${VITE_GEMINI_API_KEY_16:-}
        - VITE_GEMINI_API_KEY_17=${VITE_GEMINI_API_KEY_17:-}
    container_name: app-generator-prod
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - msbross_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appgenerator.rule=Host(`appgen.manuelalvarez.dev`)"
      - "traefik.http.routers.appgenerator.entrypoints=websecure"
      - "traefik.http.routers.appgenerator.tls.certresolver=myresolver"
      - "traefik.http.routers.appgenerator.priority=999"
      - "traefik.http.services.appgenerator.loadbalancer.server.port=80"
      - "traefik.docker.network=msbross_net"

networks:
  msbross_net:
    external: true
