server {
    listen 80;
    server_name _;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Soporte para React Router (SPA)
        try_files $uri $uri/ /index.html;
    }

    # Caché para assets estáticos
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }
}
